### ISSUE TITLE
Issues with reproducing the results in Table 3 of the paper

### ISSUE THREAD

**Issue by rumi-09** [acbull/LADIES#8]
Hi,
I was trying to reproduce the same set of results with the same datasets with your code. Though the accuracy mean and variance for 10 experiments gives almost the same result, the total time and batch number do not match. I also wonder how these two results are quite different for batch size 64 and 512. Could you please upload the final version of your code where you calculate these results or give an insight on how can I reproduce these results?

Thanks!

**Comment by acbull** [comment]
Hi:

For the time, I'm not sure whether the experiment device will matter. Our setting is a single V100 GPU.

For batch number, what is the result of your experiment? 

The difference with batch size (actually sampled number) 64 and 512 is because the more nodes we sample, the more accurate we should get to estimate node representations.

**Comment by rumi-09** [comment]
Hi,
Thanks for your quick response. For cora dataset, I get the following results:
sample number = 64
accuracy ----- mean:  78.76953125  variance:  1.6483306884765625
batch num ----- mean:  86.0  variance:  3764.0
total time ------ mean:  2.6054623126983643  variance:  0.2424971151405316

sample number = 512
accuracy ----- mean:  80.05859375  variance:  0.9189605712890625
batch num ----- mean:  32.0  variance:  936.0
total time ------ mean:  2.2203045129776  variance:  0.08504224714882241

Do these results make any sense to you? I am really confused about what I am doing wrong. Can you give me any suggestions?

**Comment by acbull** [comment]
For total time, I think it's because of the device difference.

For batch number, I think your question is that the batchnum you get is lower than our table. This is because we have a threshold in my current implementation (args.n_stops = 200) as a upper bound for early stop. I think you can remove it, and it should get the similar result. But I would admit that the result is exactly not that stable, with a relatively high variance.

**Comment by rumi-09** [comment]
The results reported in the paper, are they for the same set of parameters (epoch, batch_num, n_stops)? Especially for samp_num 64 and 512 did you use the same epoch, batch_num, and n_stops?

**Comment by acbull** [comment]
Yes. You can just remove n_stops.

**Comment by rumi-09** [comment]
Hi, thanks so much for your help. I was able to get similar results for cora, citeseer and pubmed dataset. Now I am trying to do the same for reddit dataset. But it seems running on reddit dataset is very slow. Is it common? And for testing, my code is generating "CUDA out of memory" error. I was wondering if you faced the same issue and can give me any suggestions?

**Comment by acbull** [comment]
In that case, you can reduce the sampled_size.

**Comment by rumi-09** [comment]
Thank you so much for all the help.
